spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    username: rdutta
    password: Prerna12345
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
      show-sql: 'true'
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  application:
    name: identity-manager
server:
  port: 8082
